### ISSUE TITLE
Thanks and questions

### ISSUE THREAD

**Issue by Philip2809** [ghokun/appletv3-iptv#13]
Thank you for this awesome project, got a free ATV3 when I bought my tv and can hopefully bring some life to it by using this, wanted to jailbreak and use kodi but this is even better! 

I can confirm it works on A1469 with software version 7.9 (8163). A couple of questions that came to mind was could you replace any of the other apps as well? The structure for the xml, is there any documentation for that whatsoever or its just trial and error (and by looking into the other github repos you have linked)?

**Comment by ghokun** [comment]
Hey @Philip2809, thanks for the interest. I believe you can intercept other apps as well. A quick github search would give you some hints about it: https://github.com/wahlmanj/OpenPlex/blob/99d7effcd5d2f17caf1d08ff74a95bd72cd5b4f2/update/OSX/WebServer.py#L160

Alternatively you can reset your Apple TV and place a DNS server and intercept the actual queries done by Apple TV to discover the urls.

**Comment by ghokun** [comment]
More info here:

https://github.com/iBaa/PlexConnect/pull/513#issuecomment-367529826

**Comment by ghokun** [comment]
You can find the example XML's from here: https://github.com/wahlmanj/sample-aTV

**Comment by Philip2809** [comment]
thank your for your quick answers, will look more into this, have some ideas on stuff I can do with this, thanks for sharing :D
