### ISSUE TITLE
would this still work on OS7.9?

### ISSUE THREAD

**Issue by devalanche** [ghokun/appletv3-iptv#9]
hi, got a raspberrypi 4 with pihole and unbound and an appletv 3 (1469) running os7.9.

before I give it a try I'd like to ask if anyone got it running on os7.9 yet or if Apple or redbull.tv closed the door with the latest versions

**Comment by ghokun** [comment]
I have not checked, but if the redbull.tv app is there. It should work.

**Comment by devalanche** [comment]
ok, actually trying this.

what I got so far:

- profile on appletv
- your app is running on my raspberrypi

what is missing:
i guess the route from appletv.redbull.tv is not configured properly.

i get routed to the document-root of my pi what tells me the the dns record seems to work. but appletv seems not able to find the app yet.

Got a clue?

**Comment by ghokun** [comment]
Which DNS does your apple tv use? You may need to manually set it through network settings.

**Comment by devalanche** [comment]
thanks for your prompt answers, mate. i hope I don't bother you too much. just tell me, if so... np


dns in appletv settings is my rasppi:

![image](https://github.com/ghokun/appletv3-iptv/assets/38611559/07863827-5b95-4ce9-bdd2-c0a5a8ac038e)

when i use the browser for appletv.redbull.tv i get to the document root of my lighttpd server. I even placed the app there (/var/www/html) for testing. but i still get no xml content

![image](https://github.com/ghokun/appletv3-iptv/assets/38611559/8f7fda08-6cc2-44d3-88e6-c5ccab7422cc)

**Comment by devalanche** [comment]
ok, i enabled the cgi for lighttpd and placed and started appletv3-iptv from /usr/lib/cgi-bin as written in the lighttpd docs.

now i can access the xml und appletv.redbull.tv:<custom-http-port>

now apple tv itself leads me to the true redbull content again lol... this bitch

Guess i have to forward the custom ports somehow

**Comment by devalanche** [comment]
just set pihole admin to 8080 so port 80 is free for iptv - works. Thanks so much, loving it ;)

**Comment by ghokun** [comment]
I am glad you were able to set it up. Enjoy it!
